name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2
- pandas
- numpy
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
  - torch
  - torchvision
  - horovod==0.16.4
  - pillow
  - fire
  - tensorboardX
  - tqdm
  - h5py
  - opencv-python-headless
  
channels:
- conda-forge
- anaconda
